# Generated by Django 4.2.11 on 2024-03-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autority_points', models.FloatField(default=0.0)),
                ('frequency_points', models.FloatField(default=0.0)),
                ('tags_points', models.FloatField(default=0.0)),
                ('auto_reference_penalty', models.FloatField(default=0.0)),
                ('fresh_points', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Link Externo')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Titulo')),
                ('index', models.URLField(verbose_name='URL da Página')),
                ('date', models.DateField(null=True, verbose_name='Data de Publicação')),
                ('content', models.TextField(default='', verbose_name='Conteúdo Html')),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buscador.evaluation')),
                ('external_links', models.ManyToManyField(to='buscador.externallink')),
            ],
        ),
    ]
